### ISSUE TITLE
Code Review for An Sheng

### ISSUE THREAD

**Issue by ongweisheng** [AY2122S1-CS2113T-T12-3/tp#119]
1. 
![image](https://user-images.githubusercontent.com/57165946/138803486-c9af7b22-e9e7-4344-b680-daa159de1e2a.png)
Perhaps have a separate Constant class to store all these different constants as well as from other classes to keep your current class more clean.

2. More javadoc comments for functions/methods that are more complicated.

**Comment by AnShengLee** [comment]
Got it thank you!
