### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by ongweisheng** [AY2122S1-CS2113T-T12-3/tp#147]
![image](https://user-images.githubusercontent.com/57165946/139185777-e6d115e9-1b51-4fca-916d-c950af24cdb2.png)
1. Perhaps the boxes do not have to have 2 rows as this is an architecture diagram. It would be clearer to join have the class/components name. If not it make look like a modified class diagram
2. Also mentioned in your existing comments that the arrows can be quite confusing. Perhaps can rearrange the boxes to have lesser overlapping lines.
3. 
![image](https://user-images.githubusercontent.com/57165946/139186533-400c3013-fb75-44da-9677-8fc854606c41.png)
Some bugs with the image link
4. 
![image](https://user-images.githubusercontent.com/57165946/139186627-f2e845db-30f7-4ace-ac5e-8d5464ba5b1b.png)
Missing return dotted lines after end of activation bar for the methods called.
5. 
![image](https://user-images.githubusercontent.com/57165946/139186840-d8ef2275-031f-4696-885f-2cae5e6c6cbd.png)
Dotted line should not go below the centre of the X
6. 
![image](https://user-images.githubusercontent.com/57165946/139186937-18861f45-94d5-4c7a-9671-7cc773fe081b.png)
Just fix up some of the cosmetic or links problem throughout the DG like the ##### can be seen.

**Comment by AnShengLee** [comment]
Thanks for the feedback TA. Will take note.
