### ISSUE TITLE
[PE-D] General message when commands are input without parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#152]
Expected output: Preferably, user would get a more specific error message, such as the parameters missing for each different command.

Actual output: User is getting a generic error message (shown below).

Tested inputs:
- `add_ex`
- `del_ex`
- `add_in`
- `add_ex d/test a/123`

![image.png](https://raw.githubusercontent.com/marcusbory/ped/main/files/97bf3310-501a-482c-9623-abad66840ccf.png)

![image.png](https://raw.githubusercontent.com/marcusbory/ped/main/files/bce2309e-6125-472b-8c76-4ea023c76b49.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: marcusbory/ped#1

**Comment by KZQ1999** [comment]
![image](https://user-images.githubusercontent.com/69465661/139621461-f864cfec-2b87-44cc-8352-a2731d0d169b.png)

**Comment by KZQ1999** [comment]
Did for del_ex and del_in only

**Comment by KZQ1999** [comment]
![image](https://user-images.githubusercontent.com/69465661/139623121-49631fa5-dd97-48ad-a18c-5f5673bb44ac.png)

![image](https://user-images.githubusercontent.com/69465661/139623138-1508af07-fff0-4b94-9e59-9aee1e1c8264.png)

Idea is if its a multiple part command and the argument is empty throw a missing parameter exception
Is this okay guys?

**Comment by KZQ1999** [comment]
partially fixed , not fixed for commands that require more than 1 parameter

**Comment by AnShengLee** [comment]
I will finish up the fix for this.
