### ISSUE TITLE
[PE-D] Incorrect error message when deleting using numeric index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#157]
As per the screenshot below, the input `del_ex i/0.4` is technically numeric. However, the error message appears to suggest that the inputs aren't.

This is not a serious flaw, probably related to error message.

![image.png](https://raw.githubusercontent.com/marcusbory/ped/main/files/4a6d98f1-eaaf-4ea6-ac6e-34ad2e86c2bf.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: marcusbory/ped#3

**Comment by AnShengLee** [comment]
Acknowledged will fix it thanks.
