### ISSUE TITLE
[PE-D] Code not rendered correctly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#158]
The command `del_ex i/1` is not rendered correctly in the UG.

![ug_bug3.png](https://raw.githubusercontent.com/nvbinh15/ped/main/files/15dd9fa6-27a2-4afb-bcbf-a579d61b613e.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: nvbinh15/ped#3

**Comment by KZQ1999** [comment]
done
