### ISSUE TITLE
[PE-D] Storage file `StonksXD_Settings.csv` exception not handled 2

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#173]
The program crash when the second line of `StonksXD_Settings.csv` is deleted.

![Screen Shot 2021-10-29 at 17.19.49.png](https://raw.githubusercontent.com/nvbinh15/ped/main/files/31139204-7363-4125-b35b-dd717c53deb3.png)

![Screen Shot 2021-10-29 at 17.19.56.png](https://raw.githubusercontent.com/nvbinh15/ped/main/files/799e8027-bf65-484d-bb03-2a1248c49f8d.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nvbinh15/ped#7

**Comment by AnShengLee** [comment]
Good catch will fix.
