### ISSUE TITLE
[PE-D] I'm not exactly sure about the way Budget, Expenses and Income is structured.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#175]
The way it is structured should be indicated at the start of the document, because it is not clear if Budget is the set amount of money that the user can spend or if Budget is the percentage of the income that can be spent. It is mentioned at the Budget section, but however, you should give a brief overview at the start to prevent user from being confused. 

-------------
Labels: `type.DocumentationBug` `severity.High`
original: YEOWEIHNGWHYELAB/ped#6

**Comment by KZQ1999** [comment]
This might not be duplicate now that i think about it
what this guy is saying is that we should tell them to set a budget at the start before they add an expense/income .
