### ISSUE TITLE
[PE-D] UG Introduction typo

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#178]
Should be "set/adjust" instead of "sets/adjusts".

![Screen Shot 2021-10-29 at 17.24.43.png](https://raw.githubusercontent.com/nvbinh15/ped/main/files/e0cd70ee-e806-4626-a5b5-b8638987f5fe.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: nvbinh15/ped#8

**Comment by KZQ1999** [comment]
nice one brother, done!
