### ISSUE TITLE
[PE-D] Table of content does not link properly.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#192]
The following link does not link to the section (and is the wrong date format):

![image.png](https://raw.githubusercontent.com/kelvneo/ped/main/files/4628b8b8-a228-466f-a6c7-837d54383c32.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kelvneo/ped#8

**Comment by AnShengLee** [comment]
Same as #149. I have fixed it.
